M48
; DRILL file {KiCad 8.0.5} date 2024-11-28T19:31:39+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-28T19:31:39+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0630
%
G90
G05
T1
X2.8634Y-3.7402
X3.139Y-3.7402
T2
X3.1051Y-4.4094
X3.1051Y-4.6457
M30
